### ISSUE TITLE
encoder error for some datasets while experiments

### ISSUE THREAD

**Issue by hjwilli** [EpistasisLab/pennai#222]
to reproduce, upload the ['adult'](https://github.com/EpistasisLab/penn-ml-benchmarks/blob/master/datasets/classification/adult/adult.tsv.gz) dataset with the web interface with 'sex' and 'native-country' as categorical features and run an experiment.

The experiment fails and returns the error:  `ValueError(msg)ValueError: Found Unknown Categories [15.0] In Column 1 During Transform`

The associated error log in machine is:

```
machine_1  | 0|machine  | stdout: parsed args: {'method': 'GradientBoostingClassifier', '_id': '5d4d92ec818a81003c3ed7ca', 'grid_search': False, 'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 1, 'subsample': 1.0, 'max_features': None}
machine_1  | 0|machine  | loading..
machine_1  | 0|machine  | stderr: Traceback (most recent call last):
machine_1  | 0|machine  |   File "driver.py", line 46, in <module>
machine_1  | 0|machine  |     main(args, param_grid)
machine_1  | 0|machine  |   File "driver.py", line 38, in main
machine_1  | 0|machine  |     param_grid=param_grid
machine_1  | 0|machine  |   File "/appsrc/machine/learn/skl_utils.py", line 244, in generate_results
machine_1  | 0|machine  |     return_estimator=True
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 240, in cross_validate
machine_1  | 0|machine  |     for train, test in cv.split(X, y, groups))
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 920, in __call__
machine_1  | 0|machine  |     while self.dispatch_one_batch(iterator):
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 759, in dispatch_one_batch
machine_1  | 0|machine  |     self._dispatch(tasks)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 716, in _dispatch
machine_1  | 0|machine  |     job = self._backend.apply_async(batch, callback=cb)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 182, in apply_async
machine_1  | 0|machine  |     result = ImmediateResult(func)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 549, in __init__
machine_1  | 0|machine  |     self.results = batch()
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 225, in __call__
machine_1  | 0|machine  |     for func, args, kwargs in self.items]
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 225, in <listcomp>
machine_1  | 0|machine  |     for func, args, kwargs in self.items]
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 568, in _fit_and_score
machine_1  | 0|machine  |     test_scores = _score(estimator, X_test, y_test, scorer, is_multimetric)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 605, in _score
machine_1  | 0|machine  |     return _multimetric_score(estimator, X_test, y_test, scorer)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 635, in _multimetric_score
machine_1  | 0|machine  |     score = scorer(estimator, X_test, y_test)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/metrics/scorer.py", line 91, in __call__
machine_1  | 0|machine  |     y_pred = estimator.predict(X)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/utils/metaestimators.py", line 118, in <lambda>
machine_1  | 0|machine  |     out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/pipeline.py", line 331, in predict
machine_1  | 0|machine  |     Xt = transform.transform(Xt)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/compose/_column_transformer.py", line 493, in transform
machine_1  | 0|machine  |     Xs = self._fit_transform(X, None, _transform_one, fitted=True)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/compose/_column_transformer.py", line 393, in _fit_transform
machine_1  | 0|machine  |     fitted=fitted, replace_strings=True))
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 917, in __call__
machine_1  | 0|machine  |     if self.dispatch_one_batch(iterator):
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 759, in dispatch_one_batch
machine_1  | 0|machine  |     self._dispatch(tasks)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 716, in _dispatch
machine_1  | 0|machine  |     job = self._backend.apply_async(batch, callback=cb)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 182, in apply_async
machine_1  | 0|machine  |     result = ImmediateResult(func)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 549, in __init__
machine_1  | 0|machine  |     self.results = batch()
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 225, in __call__
machine_1  | 0|machine  |     for func, args, kwargs in self.items]
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 225, in <listcomp>
machine_1  | 0|machine  |     for func, args, kwargs in self.items]
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/pipeline.py", line 605, in _transform_one
machine_1  | 0|machine  |     res = transformer.transform(X)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py", line 812, in transform
machine_1  | 0|machine  |     X_int, _ = self._transform(X)
machine_1  | 0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py", line 107, in _transform
machine_1  | 0|machine  |     raise ValueError(msg)
machine_1  | 0|machine  | ValueError: Found unknown categories [15.0] in column 1 during transform
machine_1  | 0|machine  | Experiment 5d4d92ec818a81003c3ed7ca process ended, exit code: 1, status: undefined
lab_1      | 0|lab    | serverSocket.emitEvent('expUpdated', '[object Object]')
lab_1      | 0|lab    | { collection: 'experiments', id: '5d4d92ec818a81003c3ed7ca' }
lab_1      | 0|lab    | PUT /api/v1/experiments/5d4d92ec818a81003c3ed7ca 200 15 - 2.121 ms
```

**Comment by weixuanfu** [comment]
There was only one instance with native-country=15 in the dataset. So one CV should failed due to include that instance to test set. I will refine encoder step for fixing this issue.

**Comment by weixuanfu** [comment]
I just pushed a patch (see the commit above) to fix this issue.

**Comment by hjwilli** [comment]
The patch fixed the first issue, thanks!  While testing, I found that the [tic-tac-toe](https://www.openml.org/d/50) dataset also gives an error related to labels:

![image](https://user-images.githubusercontent.com/1174948/63035217-c0252400-be88-11e9-91c2-8f379e8b1956.png)

**Comment by weixuanfu** [comment]
Hmm, I will check that. It seems that it is about encoding the target column.

**Comment by weixuanfu** [comment]
By default, recall and precision score on binary classification are calculated with a assumption that the label of `positive` is encoded as 1. So the error should raise if target column for binary classification was not encoded in this way.  One workaround is that let user to specify this information when uploading dataset in UI, like `{'class', ['neg', 'pos']}` or ` {'class', ['failed', 'pass']} ` and then PennAI can encode target column based on it.

Before UI changes, I think we need add docs about this issue for informing user to encode target column.

**Comment by hjwilli** [comment]
Ok, gotcha!  I'll update the documentation and the dataset validation for binary classification problems for now, and we can further address this in a new issue.

One more dataset oddity, this one with the [pmlb tokyo1](https://github.com/EpistasisLab/penn-ml-benchmarks/tree/master/datasets/classification/tokyo1) dataset.  These runs are from uploading with no categorical/ordinal columns.  Certain algorithm parm combinations are causing ValueError exceptions.  I suspect this issue is intermittent because different experiments have different cross validation splits:

![image](https://user-images.githubusercontent.com/1174948/63053027-c1694780-beae-11e9-8cf6-e7c7bf290bcc.png)

![image](https://user-images.githubusercontent.com/1174948/63053157-202ec100-beaf-11e9-9f5f-48f78d3fbd47.png)

The associated log:
```
0|machine  | POST /projects/5d5453f3a5df106fabcdb21e 200 103 - 10.900 ms
0|machine  | stdout: parsed args: {'method': 'SVC', '_id': '5d546a2c998898003bf7d997', 'grid_search': False, 'kernel': 'poly', 'tol': 0.001, 'C': 0.5, 'gamma': 0.1, 'degree': 3, 'coef0': 1.0}
0|machine  | method_args: {'kernel': 'poly', 'tol': 0.001, 'C': 0.5, 'gamma': 0.1, 'degree': 3, 'coef0': 1.0, 'cache_size': 700, 'max_iter': 10000}
0|machine  | loading..
0|machine  | stderr: Traceback (most recent call last):
0|machine  |   File "driver.py", line 46, in <module>
0|machine  |     main(args, param_grid)
0|machine  |   File "driver.py", line 38, in main
0|machine  |     param_grid=param_grid
0|machine  |   File "/appsrc/machine/learn/skl_utils.py", line 246, in generate_results
0|machine  |     return_estimator=True
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 240, in cross_validate
0|machine  |     for train, test in cv.split(X, y, groups))
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 917, in __call__
0|machine  |     if self.dispatch_one_batch(iterator):
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 759, in dispatch_one_batch
0|machine  |     self._dispatch(tasks)
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 716, in _dispatch
0|machine  |     job = self._backend.apply_async(batch, callback=cb)
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 182, in apply_async
0|machine  |     result = ImmediateResult(func)
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 549, in __init__
0|machine  |     self.results = batch()
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 225, in __call__
0|machine  |     for func, args, kwargs in self.items]
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 225, in <listcomp>
0|machine  |     for func, args, kwargs in self.items]
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 568, in _fit_and_score
0|machine  |     test_scores = _score(estimator, X_test, y_test, scorer, is_multimetric)
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 605, in _score
0|machine  |     return _multimetric_score(estimator, X_test, y_test, scorer)
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 635, in _multimetric_score
0|machine  |     score = scorer(estimator, X_test, y_test)
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/metrics/scorer.py", line 208, in __call__
0|machine  |     return self._sign * self._score_func(y, y_pred, **self._kwargs)
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/metrics/ranking.py", line 356, in roc_auc_score
0|machine  |     sample_weight=sample_weight)
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/metrics/base.py", line 77, in _average_binary_score
0|machine  |     return binary_metric(y_true, y_score, sample_weight=sample_weight)
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/metrics/ranking.py", line 328, in _binary_roc_auc_score
0|machine  |     sample_weight=sample_weight)
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/metrics/ranking.py", line 618, in roc_curve
0|machine  |     y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/metrics/ranking.py", line 403, in _binary_clf_curve
0|machine  |     assert_all_finite(y_score)
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 68, in assert_all_finite
0|machine  |     _assert_all_finite(X.data if sp.issparse(X) else X, allow_nan)
0|machine  |   File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
0|machine  |     raise ValueError(msg_err.format(type_err, X.dtype))
0|machine  | ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
0|machine  | Experiment 5d546a2c998898003bf7d997 process ended, exit code: 1, status: undefined
```

**Comment by weixuanfu** [comment]
I checked into this issue. With some parm combinations, the SVC might be not fitted well on training set in a CV and the [`decision_function`](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC.decision_function) would return NaNs which would be used as 'y_score' in [roc_curve](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_curve.html) scoring function for estimating AUC scores. Then the error raised due to NaNs in `y_score`.

**Comment by weixuanfu** [comment]
![image](https://user-images.githubusercontent.com/21084970/63447602-4fdb4d00-c40a-11e9-9254-1caf1a6d9fe1.png)
I pushed a new branch with the commit above to disable AUC/ROC when the scores cannot be estimated. The new result page in this case will be like the screenshot above.
Also, I found that the permutation feature importances are all 0 in the param combination on the screenshot above. So the commit above also disable feature importance plot if all importances are 0.  
Please let me know if it is OK to merge it to master branch.
